<?php

namespace App\Exceptions;

class NotFoundException extends PublicException
{
    public function getErrorCode(): string
    {
        return 'notFound';
    }

    public function getHttpCode(): int
    {
        return parent::getHttpCode(); // TODO: Change the autogenerated stub
    }

    public function getData(): mixed
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }

    public function publicMessage(): ?string
    {
        return parent::publicMessage(); // TODO: Change the autogenerated stub
    }

}
